swagger: '2.0'
info:
  description: ''
  version: Vol.1
  title: Swagger Student Login
host: 'localhost:8000'
basePath: /
tags:
  - name: Student Login
    description: เข้าสู่ระบบ
  - name: Login Report
    description: รายงานจำนวนนักเรียนในระบบ
  
  
schemes:
  - http
paths:
  /login:
    post:
      tags:
        - Student Login
      summary: ล็อกอินเข้าสู่ระบบ
      description: ''
      consumes:
        - application/x-www-form-urlencoded
      parameters:
        - in: formData
          name: email
          description: อีเมลภาค
          default: 62050001@cskmitl.ac.th
          type: string
        - in: formData
          name: password
          description: รหัสผ่าน
          default: 12345678
          type: string
        
      responses:
        '200':
          description: OK
          schema:
            properties:
              message:
                type: string
            example:
              message:  Login Success
        '400':
          description: Bad Request
          schema:
            properties:
              message:
                type: string
            example:
              [message: Don't have this account please Sign Up,
              message: Already Login,
              message: Please use cs-kmitl mail]
        '403':
          description: Forbidden
          schema:
            properties:
              message:
                type: string
            example:
              message: Wrong Password
  /report:
    get:
      tags:
        - Login Report
      responses:
        '200':
          description: OK
          schema:
            properties:
              message:
                type: string
            example:
              message:  Create Report Success
  
